# Generated by Django 2.1.9 on 2020-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=15)),
                ('Identity', models.CharField(max_length=50)),
                ('Reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Data',
            },
        ),
    ]
